version: '3'

services:
  postgresdb:
    container_name: psql
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    volumes:
      - data:/var/lib/postgres/data
    ports:
      - "5433:5432"
  
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
    environment:
     - DB_URL=host=postgresdb user=postgres password=12345 dbname=postgres port=5432 sslmode=disable
    restart: on-failure
    ports:
      - "3000:3000"
  
volumes:
  data:
