version: '3'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresDB
    environment:
      - DB_URL=host=postgresDB user=postgres password=12345 dbname=postgres port=5432 sslmode=disable
    restart: on-failure
    ports:
      - "3000:3000"
  postgresDB:
    container_name: psql
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  

  
volumes:
  data:
