apiVersion: apps/v1 
kind: Deployment                                  # Type of the kubernetes resource
metadata:
  name: api                    # Name of the Kubernetes resource
  labels:
    app: api
spec:
  replicas: 1                                     # Number of pods to run at any given time
  selector:
    matchLabels: 
      app: api                 # This deployment applies to any Pods matching the specified label
  template:                                       # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                                     # The labels that will be applied to all of the pods in this deployment
        app: api
    spec:                                         # Spec for the container which will run in the Pod
      containers:
      - name: api 
        image: manafabdulc/first-project:latest    # The image we are getting from dockerhub
        imagePullPolicy: IfNotPresent             # If we have not pulled it before, get it from dockerhub
        ports:
          - name: http
            containerPort: 3000              # Should match the port number that the Go application listens on
        envFrom:
          - secretRef:
              name: postgres-secret               # Name of the secret environmental variable file to load
        

---
apiVersion: v1  
kind: Service                                 # Type of the kubernetes resource
metadata:
  name: api                # Name of the Kubernetes resource
  labels:                                     # Labels that will be applied to the resource
    app: api
spec:
  type: NodePort                              # Gives each node an external IP that’s accessible from outside the cluster and also opens a Port.
  selector:
    app: api               # Selects any Pod with labels `app=fullstack-app-postgres`
  ports: 
  - name: http
    port: 3000
    targetPort: 3000