apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData: 
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "12345"
  POSTGRES_DB: postgres
  
  DB_URL: "host=postgresdb user=postgres password=12345 dbname=postgres port=5432 sslmode=disable"

  
  PORT: "3000"

  EMAIL: manafabdulc@gmail.com
  PASSWORD: ogskltoxjnpojeef
  SECRET_KEY: this is a super secret key

  ADMIN: manaf
  ADMIN_PASSWORD: m+-an*f@0101

  RAZOR_kEY: rzp_test_POal0vTnLIUmtn
  RAZOR_SECRET: eHWci0YKnLWGaOzXb9xMglJm